services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_finance
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - ./db/qdrant_storage:/qdrant/storage
    restart: unless-stopped
